language: node_js
node_js: node
os: linux
dist: trusty
sudo: required
install:
  - npm install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
script:
  - npm test
  - npm run gulp comp
  - npm run gulp dist
  - npm run gulp clean
after_success:
  - sh -e /etc/init.d/xvfb stop
after_failure:
  - sh -e /etc/init.d/xvfb stop
before_deploy:
  - sudo dpkg --add-architecture i386
  - wget -q -O - https://dl.winehq.org/wine-builds/Release.key | sudo apt-key add -
  - sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
  - sudo apt-get update
  - sudo apt-get install --install-recommends winehq-stable -y
  - npm run pack
  - zip -9 -r gijitron-win32-x64.zip gijitron-win32-x64
  - zip -9 -r gijitron-darwin-x64.zip gijitron-darwin-x64
  - zip -9 -r gijitron-linux-x64.zip gijitron-linux-x64
deploy:
  provider: releases
  api_key:
    secure: e9XfUJMpzMWanD4Ws3gknIkXZ1KRot7h/Oz/kTRGciPzqQ/vKCxx6BZ2eyJtUKqTkGu5zNBLztbu6P7xdg4WqyWdU3P6lb58awyDc/qcutQmrrhuC1+HHkkCucAGV+abHrQHCqbDFkNf+M/Gckm1PWP9JCHV1BpIxO7T8rYBLeDbM8lvXFBX7P8lC6Afwb84zN5FNeuABmdZAvBleXAJcXJjy5QW3xc4HnG5bYuXdD4YwW69ZONbUwcwtbszDYqF3P4e1dZZqGcvsErkMxZOWeVQn7peWQXfulBrsSG3BwvM6UANbQeQdMlc1cF+WTS6AAaXqhTuwfohKR7h7A67lktI/btCQZXdFe0v37Un3SitII/MsitHOMinCE6fEPHOVnp39P/oefPNPCLWjbGy1ueGdQ9oQSbs8TERDhRmUwQ4N8Yfo5mW+1ZtMS7VUC33iO3NYK8JxbzrSSO5Vb8wj+y4Io/VWKj/nR8fN3xV/1/XLGoO3zdqb5q+XtCTmQwzRJPP9G2unAf4brNuUmIu0pSDXeN6Wzqi84APbl4UudbyWKKycymuGfbEwsHVRI8j4NifDbAQY3csq3A2qL0gZEmXwHxrXU+D/Yv/bwlsaaH4HvyM9dN1q17rHDI3K1L3D6k1fBgm2yIVoZ/e6VLFQ52BkeqdsaAQH0B0V9kZVqs=
  file:
    - gijitron-win32-x64.zip
    - gijitron-darwin-x64.zip
    - gijitron-linux-x64.zip
  skip_cleanup: true
  on:
    tags: true
    branch: master